<a href="https://colab.research.google.com/github/vitorwmoutinho/projeto1aprender/blob/main/M%C3%B3dulo_2_Python_para_a_an%C3%A1lise_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introdução e criação de arrays

Numpy Import

In [ ]:
#Importar a biblioteca
import numpy as np

In [ ]:
np.array?

In [ ]:
#Criação de array 1D
l = [1, 2, 3]
x = np.array(l)
print("x:", x)
print("Shape", x.shape)

x: [1 2 3]
Shape (3,)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
# criação de um array 2D: listas aninhadas
l = [[1, 2], [3, 4]]
x = np.array(l)
print("X:\n", x)
print("shape", x.shape)

X:
 [[1 2]
 [3 4]]
shape (2, 2)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
# Array contendo 0's
dim = (2, 2) # (linha, Colunas)
x = np.zeros(dim)
print("x:\n", x)
print("Shape:", x.shape)

x:
 [[0. 0.]
 [0. 0.]]
Shape: (2, 2)


In [ ]:
# Array contendo 1's
size = (2, 2)
x = np.ones(size)
print("X:\n", x)
print("Shape:", x.shape)

X:
 [[1. 1.]
 [1. 1.]]
Shape: (2, 2)


In [ ]:
np.linspace?

In [ ]:
# Criação de valores dentro do intervalo
# Valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start= x_min, stop = x_max, num=17, dtype=float)
print("X:", x)
print("Shape", x.shape)

X: [ 5.     5.625  6.25   6.875  7.5    8.125  8.75   9.375 10.    10.625
 11.25  11.875 12.5   13.125 13.75  14.375 15.   ]
Shape (17,)


In [ ]:
# Criação da matriz indentidade
# Matriz quadrada
n = 4
x = np.eye(n)
print("x:\n", x)
print("Shape:", x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)


In [ ]:
# Criação de valores aleatórios
# np.ramdom.seed(10)
x = np.random.random(size=(2, 3))
print("X:\n", x)
print("Shape:", x.shape)

X:
 [[0.28577965 0.57546843 0.05812473]
 [0.03899871 0.31990569 0.46205203]]
Shape: (2, 3)


Indexação