<a href="https://colab.research.google.com/github/vitorwmoutinho/projeto1aprender/blob/main/M%C3%B3dulo_2_Python_para_a_an%C3%A1lise_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introdução e criação de arrays

Numpy Import

In [1]:
#Importar a biblioteca
import numpy as np

In [2]:
np.array?

In [3]:
#Criação de array 1D
l = [1, 2, 3]
x = np.array(l)
print("x:", x)
print("Shape", x.shape)

x: [1 2 3]
Shape (3,)


In [23]:
type(x)

numpy.ndarray

In [26]:
# criação de um array 2D: listas aninhadas
l = [[1, 2], [3, 4]]
x = np.array(l)
print("X:\n", x)
print("shape", x.shape)

X:
 [[1 2]
 [3 4]]
shape (2, 2)


In [5]:
type(x)

numpy.ndarray

In [8]:
# Array contendo 0's
dim = (2, 2) # (linha, Colunas)
x = np.zeros(dim)
print("x:\n", x)
print("Shape:", x.shape)

x:
 [[0. 0.]
 [0. 0.]]
Shape: (2, 2)


In [11]:
# Array contendo 1's
size = (2, 2)
x = np.ones(size)
print("X:\n", x)
print("Shape:", x.shape)

X:
 [[1. 1.]
 [1. 1.]]
Shape: (2, 2)


In [12]:
np.linspace?

In [16]:
# Criação de valores dentro do intervalo
# Valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start= x_min, stop = x_max, num=6)
print("X:", x)
print("Shape", x.shape)

X: [ 5.  7.  9. 11. 13. 15.]
Shape (6,)


In [20]:
# Criação da matriz indentidade
# Matriz quadrada
n = 7
x = np.eye(n)
print("x:\n", x)
print("Shape:", x.shape)

x:
 [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
Shape: (7, 7)


In [22]:
# Criação de valores aleatórios
# np.ramdom.seed(10)
x = np.random.random(size=(2, 3))
print("X:\n", x)
print("Shape:", x.shape)

X:
 [[0.4993356  0.37281002 0.70981245]
 [0.29202681 0.08167815 0.2885805 ]]
Shape: (2, 3)
