<a href="https://colab.research.google.com/github/vitorwmoutinho/projeto1aprender/blob/main/M%C3%B3dulo_2_Python_para_a_an%C3%A1lise_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introdução e criação de arrays

Numpy Import

In [ ]:
#Importar a biblioteca
import numpy as np

In [ ]:
np.array?

In [ ]:
#Criação de array 1D
l = [1, 2, 3]
x = np.array(l)
print("x:", x)
print("Shape", x.shape)

x: [1 2 3]
Shape (3,)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
# criação de um array 2D: listas aninhadas
l = [[1, 2], [3, 4]]
x = np.array(l)
print("X:\n", x)
print("shape", x.shape)

X:
 [[1 2]
 [3 4]]
shape (2, 2)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
# Array contendo 0's
dim = (2, 2) # (linha, Colunas)
x = np.zeros(dim)
print("x:\n", x)
print("Shape:", x.shape)

x:
 [[0. 0.]
 [0. 0.]]
Shape: (2, 2)


In [ ]:
# Array contendo 1's
size = (2, 2)
x = np.ones(size)
print("X:\n", x)
print("Shape:", x.shape)

X:
 [[1. 1.]
 [1. 1.]]
Shape: (2, 2)


In [ ]:
np.linspace?

In [ ]:
# Criação de valores dentro do intervalo
# Valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start= x_min, stop = x_max, num=17, dtype=float)
print("X:", x)
print("Shape", x.shape)

X: [ 5.     5.625  6.25   6.875  7.5    8.125  8.75   9.375 10.    10.625
 11.25  11.875 12.5   13.125 13.75  14.375 15.   ]
Shape (17,)


In [ ]:
# Criação da matriz indentidade
# Matriz quadrada
n = 4
x = np.eye(n)
print("x:\n", x)
print("Shape:", x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)


In [ ]:
# Criação de valores aleatórios
# np.ramdom.seed(10)
x = np.random.random(size=(2, 3))
print("X:\n", x)
print("Shape:", x.shape)

X:
 [[0.28577965 0.57546843 0.05812473]
 [0.03899871 0.31990569 0.46205203]]
Shape: (2, 3)


Indexação

In [ ]:
# os Indices no python vão de 0 a n -1
#onde n é o tamnho da dimensão
x = np.linspace(start= 10, stop=100, num=10)
print("x:", x)
print("shape:", x.shape)

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape: (10,)


In [ ]:
#extração de elementos
print("x:", x)
print("Primeiro", x[0])
print("ultimo", x[-1])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Primeiro 10.0
ultimo 100.0


In [ ]:
x[-]

80.0

In [ ]:
#slicing extração de subarrays
print("x:", x)
print("Extraindo o primeiro", x[0:2]) # 2 é exclusivo
# omitindo o 0
print("Extraindo o zero", x[:3])
print("dois ultimos", x[-2:])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Extraindo o primeiro [10. 20.]
Extraindo o zero [10. 20. 30.]
dois ultimos [ 90. 100.]


In [ ]:
#slicing em 2D (matrizes)
x = x.reshape(2, 5) # 2 linhas 5 colunas
print("x:\n", x)

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [ ]:
#extração ode elementos
print("primeira linha, segunda linha", x[0, 1])


primeira linha, segunda linha 20.0


In [ ]:
print(x)

[[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [ ]:
#slicing: extração de subarrays
print("x:\n", x)
print("primera linha inteira", x[0, :])
print("ultima linha inteira:\n", x[:, [-1]])

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
primera linha inteira [10. 20. 30. 40. 50.]
ultima linha inteira:
 [[ 50.]
 [100.]]


In [ ]:
# Atenção ao compartilhamento de memoria de subarrays
x = np.array([1, 2, 3])
print("x antes", x)
y = x[:2]
y[0] = 100 # altera ao valor de x
print("depois:", x)

x antes [1 2 3]
depois: [100   2   3]


In [ ]:
# Atenção ao compartilhamento de memoria de subarrays
x = np.array([1, 2, 3])
print("x antes", x)
y = x[:2].copy() #metodo .copy não altera o valor de y
y[0] = 100 # não altera ao valor de x
print("depois:", x)

x antes [1 2 3]
depois: [1 2 3]
