<a href="https://colab.research.google.com/github/vitorwmoutinho/projeto1aprender/blob/main/M%C3%B3dulo_2_Python_para_a_an%C3%A1lise_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introdução e criação de arrays

Numpy Import

In [1]:
#Importar a biblioteca
import numpy as np

In [ ]:
np.array?

In [ ]:
#Criação de array 1D
l = [1, 2, 3]
x = np.array(l)
print("x:", x)
print("Shape", x.shape)

x: [1 2 3]
Shape (3,)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
# criação de um array 2D: listas aninhadas
l = [[1, 2], [3, 4]]
x = np.array(l)
print("X:\n", x)
print("shape", x.shape)

X:
 [[1 2]
 [3 4]]
shape (2, 2)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
# Array contendo 0's
dim = (2, 2) # (linha, Colunas)
x = np.zeros(dim)
print("x:\n", x)
print("Shape:", x.shape)

x:
 [[0. 0.]
 [0. 0.]]
Shape: (2, 2)


In [ ]:
# Array contendo 1's
size = (2, 2)
x = np.ones(size)
print("X:\n", x)
print("Shape:", x.shape)

X:
 [[1. 1.]
 [1. 1.]]
Shape: (2, 2)


In [ ]:
np.linspace?

In [ ]:
# Criação de valores dentro do intervalo
# Valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start= x_min, stop = x_max, num=17, dtype=float)
print("X:", x)
print("Shape", x.shape)

X: [ 5.     5.625  6.25   6.875  7.5    8.125  8.75   9.375 10.    10.625
 11.25  11.875 12.5   13.125 13.75  14.375 15.   ]
Shape (17,)


In [ ]:
# Criação da matriz indentidade
# Matriz quadrada
n = 4
x = np.eye(n)
print("x:\n", x)
print("Shape:", x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)


In [ ]:
# Criação de valores aleatórios
# np.ramdom.seed(10)
x = np.random.random(size=(2, 3))
print("X:\n", x)
print("Shape:", x.shape)

X:
 [[0.28577965 0.57546843 0.05812473]
 [0.03899871 0.31990569 0.46205203]]
Shape: (2, 3)


Indexação

In [ ]:
# os Indices no python vão de 0 a n -1
#onde n é o tamnho da dimensão
x = np.linspace(start= 10, stop=100, num=10)
print("x:", x)
print("shape:", x.shape)

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape: (10,)


In [ ]:
#extração de elementos
print("x:", x)
print("Primeiro", x[0])
print("ultimo", x[-1])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Primeiro 10.0
ultimo 100.0


In [ ]:
x[-3]

80.0

In [ ]:
#slicing extração de subarrays
print("x:", x)
print("Extraindo o primeiro", x[0:2]) # 2 é o numero exclusivo
# omitindo o primeiroo elemento
print("Extraindo o zero", x[:3])
print("dois ultimos", x[-2:])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Extraindo o primeiro [10. 20.]
Extraindo o zero [10. 20. 30.]
dois ultimos [ 90. 100.]


In [ ]:
#slicing em 2D (matrizes)
#reshape muda a forma do array
x = x.reshape(2, 5) # 2 linhas 5 colunas
print("x:\n", x)

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [ ]:
#extração ode elementos
print("primeira linha, segunda linha", x[0, 1])
print("Segunda linha, penultima coluna", x[1:-2])

primeira linha, segunda linha 20.0
Segunda linha, penultima coluna []


In [ ]:
print(x)

[[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [ ]:
#slicing: extração de subarrays
print("x:\n", x)
print("primera linha inteira", x[0, :])
print("ultima coluna inteira:\n", x[:, [-1]])

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
primera linha inteira [10. 20. 30. 40. 50.]
ultima coluna inteira:
 [[ 50.]
 [100.]]


In [ ]:
#Slicing compartilha mémoria com o array original

In [ ]:
# Atenção ao compartilhamento de memoria de subarrays
x = np.array([1, 2, 3])
print("x antes", x)
y = x[:2]
y[0] = -100 # altera ao valor de x
print("depois:", x)

x antes [1 2 3]
depois: [-100    2    3]


In [ ]:
# Atenção ao compartilhamento de memoria de subarrays
x = np.array([1, 2, 3])
print("x antes:", x)
y = x[:2].copy() #metodo .copy faz uma cópia não altera o valor de y
y[0] = 100 # não altera ao valor de x
print("depois:", x)

x antes: [1 2 3]
depois: [1 2 3]


**Operações Aritimeticas**



*   operações elemento por elemento
*   Broadcasting
*   Operações Matriciais



In [ ]:
#Criação de dois arrays x e y
x = np.ones((2, 2))
y = np.eye(2)
print("x: \n", x)
print("y: \n", y)

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [ ]:
# Soma
print("Soma de dois arrays: \n", x + y)
print("Soma com float/int: \n", x + 2.)

Soma de dois arrays: 
 [[2. 1.]
 [1. 2.]]
Soma com float/int: 
 [[3. 3.]
 [3. 3.]]


In [ ]:
#subtração
print("Subtração de dois arrays: \n", x - y)
print("Subtração com float/int: \n", x - 2) # broadcasting

Subtração de dois arrays: 
 [[0. 1.]
 [1. 0.]]
Subtração com float/int: 
 [[-1. -1.]
 [-1. -1.]]


In [ ]:
#divisão
##print("Divisão de dois arrays: \n", x / y)
print("Divisão com float/int: \n", x / 2) #broadcasting

Divisão com float/int: 
 [[0.5 0.5]
 [0.5 0.5]]


In [ ]:
#Quando o broadcasting não funciona
##p.array([1, 2, 3]) + np.array([1, 2])

In [ ]:
#Soma subtração e divisão
print("Combinação de operações: \n", (x + y)/(x - 2))

Combinação de operações: 
 [[-2. -1.]
 [-1. -2.]]


In [ ]:
# Multiplicação
print("Multiplicação com arrays: \n", x * y)
print("Multiplicação com float/int:\n", x * 2) #broadcasting

Multiplicação com arrays: 
 [[1. 0.]
 [0. 1.]]
Multiplicação matricial:
 [[2. 2.]
 [2. 2.]]


In [ ]:
#criando um array customizado 5 x 5, 10x10 com valor 10 DICA!!
10 * np.ones((5, 5))

In [ ]:
#Multiplicação matricial
print("multiplicação matricial (np.dot): \n", np.dot(x, y))
print("multiplicação matricial (@):\n", x @ y )
print("Multiplicação matricial .dot:\n", x.dot(y) )


multiplicação matricial (np.dot): 
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (@):
 [[1. 1.]
 [1. 1.]]
Multiplicação matricial .dot:
 [[1. 1.]
 [1. 1.]]


In [ ]:
"""
Exemplo:
Solução de um sistema de equações:
  a + 2*b = 7
  3*a - 2*b = -11
  solução analitica: (a, b) = (-1, 4)
Matricialmente este problema tem a seguinte forma:
Ax = c, onde:
 - x = [a, b]
 - A = [[1, 2], [3, -2]]
 - c = [7, -11]
 Solução númerica = x = inv(A) @ c.
 """

#definição do problema
A = np.array([[1, 2], [3, -2]])
c = np.array([[7], [-11]])
print("A: \n", A)
print("c: \n", c)

A: 
 [[ 1  2]
 [ 3 -2]]
c: 
 [[  7]
 [-11]]


In [ ]:
np.linalg

<module 'numpy.linalg' from '/usr/local/lib/python3.10/dist-packages/numpy/linalg/__init__.py'>

In [ ]:
#Solução
x = np.dot(np.linalg.inv(A), c)
print("a, b:", x.ravel())

a, b: [-1.  4.]


Comparações


*   Comparação menor/maior ou igual:




In [2]:
#comparações boolenanas
A = np.array([1, 2, 3])
B = np.array([2, 0, 2])
s = 3

In [ ]:
# menor
print("Comapração menor:")
print(A < B)
print(A < s)

# menor ou igual
print("Comparação menor ou igual:")
print(A <= B)
print(A <= s)


Comapração menor:
[ True False False]
[ True  True False]
Comparação menor ou igual:
[ True False False]
[ True  True  True]


In [ ]:
# Maior
print("Comparação maior:")
print(A > B)
print(A > s)

# Maior ou igual
print("Comapração maior ou igual:")
print(A >= B)
print(A >= s)

Comparação maior:
[False  True  True]
[False False False]
Comapração maior ou igual:
[False  True  True]
[False False  True]


In [ ]:
# Igual
print("Comapração de igualdade")
print(A == B)
print(A == s)

Operação de filtro

In [5]:
# Indexação booleana: um novo subarray contendo uma
#cópia dos elementos em que a condição de verificação se aplica
cond = A <= 2
D = A[cond]
print("A:", A)
print("Condição:", cond)
print("D:", D)

A: [1 2 3]
Condição: [ True  True False]
D: [1 2]


Comparações

In [9]:
# Criação de arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([1.5, 3.5])
print("X:\n",x)
print("Y:\n",y)

X:
 [[1 2]
 [3 4]]
Y:
 [1.5 3.5]


In [16]:
#Comparações ponto a ponto
#print("Comparação de um array com um escalar (>):\n", x > 2 )
#print("Comapração de um array com um escalar (>=):\n", x >= 2)
#print("Comapração de um array com escalar (<):\n", x < 2)
#print("Comapração de um array com escalar (<=):\n", x <= 2)
print("Comparaçlão entre arrays:\n", x > x)
print("comparação entre arrays:\n", x == x)
print("comparação entre arrays:\n", x > y) #broadcasting

Comparaçlão entre arrays:
 [[False False]
 [False False]]
comparação entre arrays:
 [[ True  True]
 [ True  True]]
comparação entre arrays:
 [[False False]
 [ True  True]]
